scene_name: 'v16'
base_img_path: ''
debug: true

prompt: 'A highly detailed photorealistic render of a modern apartment, oak wood floors, white minimalist walls, natural cinematic lighting, 4k image'
aux_prompt: ''
depth_estimator:
  mode: "indoor"

env_id: '6VSV7_695'
floor_number: '0' 